/**
 * Mock LLM
 *
 * Simule la réponse d'un LLM pendant que l'accès
 * AWS Bedrock n'est pas encore disponible.
 *
 * Plus tard, ce fichier sera remplacé par Bedrock.
 */

async function generate(prompt) {
  if (!prompt || prompt.trim().length === 0) {
    throw new Error("LLM prompt is empty");
  }

  console.log("[Mock LLM] Prompt received.");
  console.log(`[Mock LLM] Prompt length: ${prompt.length} characters`);

  /*
   * IMPORTANT :
   * Le mock ne prétend pas être Amazon Nova.
   *
   * Il permet uniquement de tester le pipeline :
   *
   * Prompt → LLM → Playwright test
   */

  const test = `
// ============================================================
// GENERATED PLAYWRIGHT TEST
// ============================================================
// Generated by Mock LLM
//
// IMPORTANT:
// This is a MOCK response.
// It will later be generated by Amazon Nova Lite.
// ============================================================

import { test, expect } from '@playwright/test';

test('Créer un utilisateur', async ({ page }) => {

  // ==========================================================
  // MISSING INFORMATION
  // ==========================================================

  // The source code does not provide:
  // - the exact frontend route
  // - stable selectors for the form fields
  //
  // Therefore the test does NOT invent them.

  const EMAIL_SELECTOR = 'SELECTOR_NOT_FOUND';
  const PASSWORD_SELECTOR = 'SELECTOR_NOT_FOUND';

  // ==========================================================
  // OPEN APPLICATION
  // ==========================================================

  // FRONTEND_ROUTE_NOT_FOUND
  //
  // The exact frontend route is not provided by the source code.
  //
  // Therefore we intentionally do not call page.goto()
  // with an invented URL.

  throw new Error(
    'FRONTEND_ROUTE_NOT_FOUND: The source code does not provide the exact frontend entry route.'
  );

  // ==========================================================
  // USER CREATION
  // ==========================================================

  // The source code confirms that the application uses:
  //
  // createUser(
  //   userInput: {
  //     email,
  //     password,
  //     role
  //   }
  // )
  //
  // However, the exact DOM selectors are not available.

  // SELECTOR_NOT_FOUND

  // ==========================================================
  // EMAIL
  // ==========================================================

  // EMAIL_TEST_MECHANISM_NOT_PROVIDED
  //
  // The application sends a confirmation email,
  // but no deterministic test mailbox is available.
  //
  // Therefore:
  // - do not open Gmail
  // - do not invent an email selector
  // - do not invent a confirmation token
  // - do not call confirmUser automatically
  // - do not call resendConfirmationEmail
});

`;

  return test;
}

module.exports = {
  generate
};